### ISSUE TITLE
Velocity

### ISSUE THREAD

**Issue by sard0r** [PIC4SeR/MPOSE2021_Dataset#5]
Good job @simoneangarano and thank you.

I just wanted to ask how do you get velocity features from the openpose pose estimation? do you subtract x2-y2 to get the velocity?

And do you have an inference.py possible or pretrained model for the purpose of testing.

Thank you very much.

**Comment by simoneangarano** [comment]
Hi @sard0r,
Yes, the velocities are computed as the difference between coordinates at successive time instants.
To test our model please refer to https://github.com/PIC4SeR/AcT
