### ISSUE TITLE
Prepare own custom dataset documentation

### ISSUE THREAD

**Issue by pranavgundewar** [PIC4SeR/MPOSE2021_Dataset#6]
Thank you for creating this repo. I would like to know the steps to prepare our custom dataset and how to create labels to use MPOSE for pose estimation dataset creation.

**Comment by simoneangarano** [comment]
Hi! MPOSE is a complete and working dataset already. You can generate the dataset and then select only labels that apply to your specific problem. Is that what you were suggesting?
I hope this helps!

**Comment by Amr411996** [comment]
thanks for sharing this great effort.
I have a dataset for action classification which have different labels, what is the steps to make the RGB images to be input for the model?
I mean what the steps to create a new dataset?

thanks in advanced

**Comment by simoneangarano** [comment]
Ok, it depends on what model you want to use! If it's going to be an RGB-based HAR model, you will have to transform your videos into sequences of frames and feed them into your model accordingly. If you are interested in skeleton-based HAR, you have first to extract 2D/3D poses from RGB images (using OpenPose or PoseNet) and then train a network to classify sequences of skeletal data. I have used the latter approach in my paper [Action Transformer: A Self-Attention Model for Short-Time Pose-Based Human Action Recognition](https://arxiv.org/abs/2107.00606). You can find the code [here](https://github.com/PIC4SeR/AcT).

**Comment by Amr411996** [comment]
Thank you!
