### ISSUE TITLE
How to select only a subset of the video datasets from the mpose API

### ISSUE THREAD

**Issue by michael1yu** [PIC4SeR/MPOSE2021_Dataset#7]
Is there anyway to select only poses generated from videos in the utkinect dataset? I would prefer to do this through the mpose api rather than building the pose dataset on my own.

**Comment by simoneangarano** [comment]
Hi @michael1yu ,
In the pose data folders (automatically downloaded by the mpose API from [here](https://doi.org/10.5281/zenodo.5506688)), you can find a txt file for each split (1.txt, 2.txt, and 3.txt) containing the name of the video corresponding to each sample. This way, you can filter the ones you want to use easily!
I hope this helps! (Sorry for the late reply, though)
